@localhost=localhost:4004/odata/v4/main
@id=140f35de-5379-48aa-a22d-4ac85f75c4c1
@customerId=140f35de-5379-48aa-a22d-4ac85f75c4c1
@productID=fbb212c2-8aee-460b-91ac-dd2388e541ff

GET http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json

###

POST http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json

{
   "id":"{{id}}",
   "customer_id": "{{customerId}}",
   "items": [
      {
         "id": "b9c3a8f0-d592-488a-ac6b-4a02444395fc",
         "header_id": "{{id}}",
         "product_id": "{{productID}}",
         "quantity": 10,
         "price": 2.99
      },
      {
         "id": "778392c2-5479-47d5-8743-13171afdcc58",
         "header_id": "{{id}}",
         "product_id": "{{productID}}",
         "quantity": 10,
         "price": 1.99
      }
   ]

}

###

PATCH  http://{{localhost}}/Customers(id={{id}})
Content-Type: application/json

###

DELETE http://{{localhost}}/Customers(id={{id}})

###

# Buscar todos os pedidos maiores ou iguais a 2 milhões
GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount ge 2000000

###

# Buscar todos os pedidos menores ou iguais a 200k
GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount le 200000

###

# Expandindo os items, produtos e customers
GET http://{{localhost}}/SalesOrderHeaders?$expand=items($expand=product),customer

###

# Expandindo os items, produtos, customers e filtrando
GET http://{{localhost}}/SalesOrderHeaders?$expand=items($expand=product;$filter=quantity le 30),customer

###

# Selecionar somente customer e id do sales order header

GET http://{{localhost}}/SalesOrderHeaders?$select=customer&$expand=customer($select=email)


###

# Descobrindo a quantidade de registros

GET http://{{localhost}}/SalesOrderHeaders/$count


###

# Paginando os registros

GET http://{{localhost}}/SalesOrderHeaders?$skip=10&$top=5

###

# Buscando dados com $search
GET http://{{localhost}}/SalesOrderHeaders?$search=91pve&$filter=totalAmount gt 500

###

# Funcionalidade de clonar pedidos
POST http://{{localhost}}/SalesOrderHeaders(15196739-2936-4d66-b85c-283f5ae8ec03)/cloneSalesOrder
Content-Type: application/json

{}