GET http://localhost:4004/odata/v4/main/SalesOrderHeaders
Content-Type: application/json

###

POST http://localhost:4004/odata/v4/main/SalesOrderHeaders
Content-Type: application/json

{}

###

DELETE http://localhost:4004/odata/v4/main/SalesOrderHeaders
Content-Type: application/json

{
   "id": "f48de019-8152-41dd-93c8-9508869b592e"
}